### ISSUE TITLE
Zoom dependent feature service not showing up in layer window / legend

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#235]
### To reproduce: 
**App URL:** https://mdg.forest-atlas.org/map?l=fr
**ArcGIS Online Webmap URL:** http://www.arcgis.com/home/webmap/viewer.html?webmap=190f6eb590914ad0971e0ed7456840d8

1. Go to the App URL: https://mdg.forest-atlas.org/map?l=fr
2. Zoom in two levels and you will see orange polygons representing mining areas. These should be visible in the layer window and the legend, but are not appearing.
3. Verify via the Webmap URL to see expected legend behavior.

### Screenshot:
![2018-10-29_15-22-02](https://user-images.githubusercontent.com/13664037/47674760-733cbf00-db8e-11e8-9b8e-dcacb1931dea.png)

**Comment by csphang** [comment]
@SwampGuzzler To confirm this is fixed, I created a copy of the original webmap and set a zoom dependency on the Orange mining polygons. They will appear two zoom levels in. Can you swap in the mapID and confirm this is fixed in the latest release?

###Copy of ArcGIS Online Webmap with Zoom Dependency Set:
https://blueraster.maps.arcgis.com/home/webmap/viewer.html?webmap=1fa27a46c2344da6ac92e33be9bf33f1

**Comment by richardbarad** [comment]
Hi @SwampGuzzler and @csphang,

Sounds like you might have already discovered this, but I removed the zoom dependency from the mining titles layer in the webmap due to this issue. I'll add it back once the fix is deployed. 

Thanks!

Best,

Richard

**Comment by SwampGuzzler** [comment]
https://beta.blueraster.io/mapbuilder/235-zoom-dependence/external.html

**Comment by csphang** [comment]
It looks like the legend doesn't load until I zoom in our out of the map. @SwampGuzzler can you check if this is happening for you?

**Comment by SwampGuzzler** [comment]
@csphang The call to AGOL that initializes the legend is taking a while, but doesn't require any zoom or extent-change. So no, I still see the legend after a couple seconds!
